return {
  "WhoIsSethDaniel/mason-tool-installer.nvim",
  lazy = false,

  dependencies = {
    "williamboman/mason.nvim",
  },

  opts = {
    ensure_installed = {
      "bashls",
      "clangd",
      "css-lsp",
      "deno",
      "dockerfile-language-server",
      "eslint-lsp",
      "gopls",
      "hadolint",
      "html-lsp",
      "jinja-lsp",
      "json-lsp",
      "lemminx",
      "lua-language-server",
      "markdown-oxide",
      "prettierd",
      "pyright",
      "roslyn",
      "ruff",
      "rust-analyzer",
      "shellcheck",
      "shellharden",
      "shfmt",
      "sqlfluff",
      "stylua",
      "taplo",
      "tailwindcss-language-server",
      "terraform-ls",
      "vim-language-server",
      -- "vue-language-server",
      "vtsls",
      "yaml-language-server",
      "yamlfmt",
      "yamllint",
    },
    auto_update = true,
    run_on_start = true,
    start_delay = 0,
  },
}
