return {
  "pwntester/octo.nvim",
  event = "VeryLazy",

  keys = {
    { "<Leader>gog", "<CMD>Octo gist list<CR>", desc = "Gists [octo]" },
    { "<Leader>goi", "<CMD>Octo issue list<CR>", desc = "Issues [octo]" },
    { "<Leader>gop", "<CMD>Octo pr list<CR>", desc = "PRs [octo]" },
    { "<Leader>gor", "<CMD>Octo repo list<CR>", desc = "Repos [octo]" },
  },

  opts = {
    suppress_missing_scope = {
      projects_v2 = true,
    },
    mappings = {
      issue = {
        close_issue = { lhs = "\\ic", desc = "Close issue [octo]" },
        reopen_issue = { lhs = "\\io", desc = "Reopen issue [octo]" },
        list_issues = { lhs = "\\il", desc = "List open issues on same repo [octo]" },
        reload = { lhs = "<C-r>", desc = "Reload issue [octo]" },
        open_in_browser = { lhs = "<C-b>", desc = "Open issue in browser [octo]" },
        copy_url = { lhs = "<C-y>", desc = "Copy url to system clipboard [octo]" },
        add_assignee = { lhs = "\\aa", desc = "Add assignee [octo]" },
        remove_assignee = { lhs = "\\ad", desc = "Remove assignee [octo]" },
        create_label = { lhs = "\\lc", desc = "Create label [octo]" },
        add_label = { lhs = "\\la", desc = "Add label [octo]" },
        remove_label = { lhs = "\\ld", desc = "Remove label [octo]" },
        goto_issue = { lhs = "\\gi", desc = "Navigate to a local repo issue [octo]" },
        add_comment = { lhs = "\\ca", desc = "Add comment [octo]" },
        delete_comment = { lhs = "\\cd", desc = "Delete comment [octo]" },
        next_comment = { lhs = "]c", desc = "Go to next comment [octo]" },
        prev_comment = { lhs = "[c", desc = "Go to previous comment [octo]" },
        react_hooray = { lhs = "\\rp", desc = "Add/remove 🎉 reaction [octo]" },
        react_heart = { lhs = "\\rh", desc = "Add/remove ❤️ reaction [octo]" },
        react_eyes = { lhs = "\\re", desc = "Add/remove 👀 reaction [octo]" },
        react_thumbs_up = { lhs = "\\r+", desc = "Add/remove 👍 reaction [octo]" },
        react_thumbs_down = { lhs = "\\r-", desc = "Add/remove 👎 reaction [octo]" },
        react_rocket = { lhs = "\\rr", desc = "Add/remove 🚀 reaction [octo]" },
        react_laugh = { lhs = "\\rl", desc = "Add/remove 😄 reaction [octo]" },
        react_confused = { lhs = "\\rc", desc = "Add/remove 😕 reaction [octo]" },
      },
      pull_request = {
        checkout_pr = { lhs = "\\po", desc = "Checkout PR [octo]" },
        merge_pr = { lhs = "\\pm", desc = "Merge commit PR [octo]" },
        squash_and_merge_pr = { lhs = "\\psm", desc = "Squash and merge PR [octo]" },
        rebase_and_merge_pr = { lhs = "\\prm", desc = "Rebase and merge PR [octo]" },
        list_commits = { lhs = "\\pc", desc = "List PR commits [octo]" },
        list_changed_files = { lhs = "\\pf", desc = "List PR changed files [octo]" },
        show_pr_diff = { lhs = "\\pd", desc = "Show PR diff [octo]" },
        add_reviewer = { lhs = "\\va", desc = "Add reviewer [octo]" },
        remove_reviewer = { lhs = "\\vd", desc = "Remove reviewer request [octo]" },
        close_issue = { lhs = "\\ic", desc = "Close PR [octo]" },
        reopen_issue = { lhs = "\\io", desc = "Reopen PR [octo]" },
        list_issues = { lhs = "\\il", desc = "List open issues on same repo [octo]" },
        reload = { lhs = "<C-r>", desc = "Reload PR [octo]" },
        open_in_browser = { lhs = "<C-b>", desc = "Open PR in browser [octo]" },
        copy_url = { lhs = "<C-y>", desc = "Copy url to system clipboard [octo]" },
        goto_file = { lhs = "gf", desc = "Go to file [octo]" },
        add_assignee = { lhs = "\\aa", desc = "Add assignee [octo]" },
        remove_assignee = { lhs = "\\ad", desc = "Remove assignee [octo]" },
        create_label = { lhs = "\\lc", desc = "Create label [octo]" },
        add_label = { lhs = "\\la", desc = "Add label [octo]" },
        remove_label = { lhs = "\\ld", desc = "Remove label [octo]" },
        goto_issue = { lhs = "\\gi", desc = "Navigate to a local repo issue [octo]" },
        add_comment = { lhs = "\\ca", desc = "Add comment [octo]" },
        delete_comment = { lhs = "\\cd", desc = "Delete comment [octo]" },
        next_comment = { lhs = "]c", desc = "Go to next comment [octo]" },
        prev_comment = { lhs = "[c", desc = "Go to previous comment [octo]" },
        react_hooray = { lhs = "\\rp", desc = "Add/remove 🎉 reaction [octo]" },
        react_heart = { lhs = "\\rh", desc = "Add/remove ❤️ reaction [octo]" },
        react_eyes = { lhs = "\\re", desc = "Add/remove 👀 reaction [octo]" },
        react_thumbs_up = { lhs = "\\r+", desc = "Add/remove 👍 reaction [octo]" },
        react_thumbs_down = { lhs = "\\r-", desc = "Add/remove 👎 reaction [octo]" },
        react_rocket = { lhs = "\\rr", desc = "Add/remove 🚀 reaction [octo]" },
        react_laugh = { lhs = "\\rl", desc = "Add/remove 😄 reaction [octo]" },
        react_confused = { lhs = "\\rc", desc = "Add/remove 😕 reaction [octo]" },
        review_start = { lhs = "\\vs", desc = "Start a review for the current PR [octo]" },
        review_resume = { lhs = "\\vr", desc = "Resume a pending review for the current PR [octo]" },
      },
      review_thread = {
        goto_issue = { lhs = "\\gi", desc = "Navigate to a local repo issue [octo]" },
        add_comment = { lhs = "\\ca", desc = "Add comment [octo]" },
        add_suggestion = { lhs = "\\sa", desc = "Add suggestion [octo]" },
        delete_comment = { lhs = "\\cd", desc = "Delete comment [octo]" },
        next_comment = { lhs = "]c", desc = "Go to next comment [octo]" },
        prev_comment = { lhs = "[c", desc = "Go to previous comment [octo]" },
        select_next_entry = { lhs = "]q", desc = "Move to next changed file [octo]" },
        select_prev_entry = { lhs = "[q", desc = "Move to previous changed file [octo]" },
        select_first_entry = { lhs = "[Q", desc = "Move to first changed file [octo]" },
        select_last_entry = { lhs = "]Q", desc = "Move to last changed file [octo]" },
        close_review_tab = { lhs = "<C-c>", desc = "Close review tab [octo]" },
        react_hooray = { lhs = "\\rp", desc = "Add/remove 🎉 reaction [octo]" },
        react_heart = { lhs = "\\rh", desc = "Add/remove ❤️ reaction [octo]" },
        react_eyes = { lhs = "\\re", desc = "Add/remove 👀 reaction [octo]" },
        react_thumbs_up = { lhs = "\\r+", desc = "Add/remove 👍 reaction [octo]" },
        react_thumbs_down = { lhs = "\\r-", desc = "Add/remove 👎 reaction [octo]" },
        react_rocket = { lhs = "\\rr", desc = "Add/remove 🚀 reaction [octo]" },
        react_laugh = { lhs = "\\rl", desc = "Add/remove 😄 reaction [octo]" },
        react_confused = { lhs = "\\rc", desc = "Add/remove 😕 reaction [octo]" },
      },
      submit_win = {
        approve_review = { lhs = "<C-a>", desc = "Approve review [octo]" },
        comment_review = { lhs = "<C-m>", desc = "Comment review [octo]" },
        request_changes = { lhs = "<C-r>", desc = "Request changes review [octo]" },
        close_review_tab = { lhs = "<C-c>", desc = "Close review tab [octo]" },
      },
      review_diff = {
        submit_review = { lhs = "\\vs", desc = "Submit review [octo]" },
        discard_review = { lhs = "\\vd", desc = "Discard review [octo]" },
        add_review_comment = { lhs = "\\ca", desc = "Add a new review comment [octo]" },
        add_review_suggestion = { lhs = "\\sa", desc = "Add a new review suggestion [octo]" },
        focus_files = { lhs = "\\e", desc = "Move focus to changed file panel [octo]" },
        toggle_files = { lhs = "\\b", desc = "Hide/show changed files panel [octo]" },
        next_thread = { lhs = "]t", desc = "Move to next thread [octo]" },
        prev_thread = { lhs = "[t", desc = "Move to previous thread [octo]" },
        select_next_entry = { lhs = "]q", desc = "Move to next changed file [octo]" },
        select_prev_entry = { lhs = "[q", desc = "Move to previous changed file [octo]" },
        select_first_entry = { lhs = "[Q", desc = "Move to first changed file [octo]" },
        select_last_entry = { lhs = "]Q", desc = "Move to last changed file [octo]" },
        close_review_tab = { lhs = "<C-c>", desc = "Close review tab [octo]" },
        toggle_viewed = { lhs = "\\\\", desc = "Toggle viewer viewed state [octo]" },
        goto_file = { lhs = "gf", desc = "Go to file [octo]" },
      },
      file_panel = {
        submit_review = { lhs = "\\vs", desc = "Submit review [octo]" },
        discard_review = { lhs = "\\vd", desc = "Discard review [octo]" },
        next_entry = { lhs = "j", desc = "Move to next changed file [octo]" },
        prev_entry = { lhs = "k", desc = "Move to previous changed file [octo]" },
        select_entry = { lhs = "<CR>", desc = "Show selected changed file diffs [octo]" },
        refresh_files = { lhs = "R", desc = "Refresh changed files panel [octo]" },
        focus_files = { lhs = "\\e", desc = "Move focus to changed file panel [octo]" },
        toggle_files = { lhs = "\\b", desc = "Hide/show changed files panel [octo]" },
        select_next_entry = { lhs = "]q", desc = "Move to next changed file [octo]" },
        select_prev_entry = { lhs = "[q", desc = "Move to previous changed file [octo]" },
        select_first_entry = { lhs = "[Q", desc = "Move to first changed file [octo]" },
        select_last_entry = { lhs = "]Q", desc = "Move to last changed file [octo]" },
        close_review_tab = { lhs = "<C-c>", desc = "Close review tab [octo]" },
        toggle_viewed = { lhs = "\\<Space>", desc = "Toggle viewer viewed state [octo]" },
      },
    },
  },
}
